In [2]:
import time
import pandas as pd
import numpy as np
import os
import os.path
from osgeo import gdal, ogr, osr
from scipy import ndimage
from scipy import misc
import cStringIO
gdal.UseExceptions()
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import gridspec
%matplotlib inline
import urllib
import utils
import shutil

In [3]:
image="../Data/google_image_matching/0/25628_8684.jpg"

In [4]:
from PIL import Image
im = Image.open(image) #Can be many different formats.
pix = im.load()
print im.size #Get the width and hight of the image for iterating over
print pix[3,3] #Get the RGBA Value of the a pixel of an image
#pix[x,y] = value # Set the RGBA Value of the image (tuple)
#im.save("alive_parrot.png") # Save the modified pixels as png

(400, 400)
(103, 107, 90)

In [5]:
A = pd.DataFrame(list(im.getdata()),columns=["R","G","B"])
A.head()

     R    G    B
0   96  103   87
1  124  131  115
2  106  110   93
3  131  135  118
4  129  133  116

In [6]:
Final=pd.DataFrame([])

In [7]:
Final=pd.DataFrame([])
dir="../Data/google_image_matching/0/"
for image in os.listdir(dir):
    if image.endswith(".jpg") : 
        im=Image.open(os.path.join(dir, image))
        A = pd.DataFrame(list(im.getdata()),columns=["R","G","B"])
        B =A.agg(["mean","median","min","max","std"])
        L=pd.DataFrame(B.unstack(),columns=["value"]).reset_index()
        L=L.set_index(L["level_0"]+"_"+L["level_1"])
        Final[image]=L["value"]

In [8]:
Final=Final.transpose().reset_index()

In [9]:
Final.head()

,index,R_mean,R_median,R_min,R_max,R_std,G_mean,G_median,G_min,G_max,G_std,B_mean,B_median,B_min,B_max,B_std
0,25628_8684.jpg,127.893106,125.0,32.0,255.0,25.594416,113.873969,113.0,37.0,236.0,15.060503,99.567837,99.0,18.0,222.0,15.128294
1,25628_8692.jpg,113.192450,111.0,32.0,255.0,18.705532,106.287500,107.0,26.0,253.0,11.499855,93.549837,94.0,15.0,241.0,12.082248
2,25629_8684.jpg,116.138437,109.0,34.0,224.0,25.154960,107.872181,106.0,33.0,174.0,13.773651,94.240463,92.0,24.0,163.0,13.824036
3,25629_8685.jpg,124.850950,119.0,29.0,255.0,27.655854,108.166600,106.0,21.0,252.0,16.931425,95.988012,94.0,12.0,241.0,16.694051
4,25631_8694.jpg,119.718050,117.0,34.0,253.0,22.157574,111.422494,111.0,31.0,236.0,15.716651,96.635419,96.0,16.0,223.0,15.607400

In [10]:
Final["i"]=Final["index"].str.slice(0,5)
Final["j"]=Final["index"].str.slice(6,10)

Final["i"]=pd.to_numeric(Final["i"])
Final["j"]=pd.to_numeric(Final["j"])

#Final = Final.drop('index', 1)

In [11]:
Final["i"]=pd.to_numeric(Final["i"])
Final["j"]=pd.to_numeric(Final["j"])

In [12]:
Final.head()

,index,R_mean,R_median,R_min,R_max,R_std,G_mean,G_median,G_min,G_max,G_std,B_mean,B_median,B_min,B_max,B_std,i,j
0,25628_8684.jpg,127.893106,125.0,32.0,255.0,25.594416,113.873969,113.0,37.0,236.0,15.060503,99.567837,99.0,18.0,222.0,15.128294,25628,8684
1,25628_8692.jpg,113.192450,111.0,32.0,255.0,18.705532,106.287500,107.0,26.0,253.0,11.499855,93.549837,94.0,15.0,241.0,12.082248,25628,8692
2,25629_8684.jpg,116.138437,109.0,34.0,224.0,25.154960,107.872181,106.0,33.0,174.0,13.773651,94.240463,92.0,24.0,163.0,13.824036,25629,8684
3,25629_8685.jpg,124.850950,119.0,29.0,255.0,27.655854,108.166600,106.0,21.0,252.0,16.931425,95.988012,94.0,12.0,241.0,16.694051,25629,8685
4,25631_8694.jpg,119.718050,117.0,34.0,253.0,22.157574,111.422494,111.0,31.0,236.0,15.716651,96.635419,96.0,16.0,223.0,15.607400,25631,8694

In [171]:
Final.to_csv("../Data/Intermediate_files/google_sat_features.csv")